### ISSUE TITLE
Generating application profile in HTML from CSV

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-SpecificationGenerator#1]
A couple of questions related to the generation of application profiles:

- Is the input CSV file based on a data dump from the Enterprise Architect database containing the UML model? If so, are there any columns to be added manually after extraction, such as domain and range?
- Using a clean installation of the tool and its dependencies on an Ubuntu 16.10 machine, running the command with the 'export_org.csv' sample files give the following error:
```
root@osboxes:/projects/digimelding/OSLO-SpecificationGenerator# ./bin/generate_vocabulary.py --csv /home/osboxes/Desktop/organisatie-ap.csv --ap --output /home/osboxes/Desktop/organisatie-ap.html

```

```
Traceback (most recent call last):
  File "./bin/generate_vocabulary.py", line 80, in <module>
    process_args()
  File "/projects/digimelding/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/projects/digimelding/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/projects/digimelding/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/digimelding/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./bin/generate_vocabulary.py", line 51, in process_args
    schema_local=schema_local)
  File "/projects/digimelding/local/lib/python2.7/site-packages/specgen-0.1.1-py2.7.egg/specgen/__init__.py", line 206, in voc_to_ap
    converted = convert_csv(csv)
  File "/projects/digimelding/local/lib/python2.7/site-packages/specgen-0.1.1-py2.7.egg/specgen/extractap.py", line 27, in convert_csv
    domains = list(set(domains) - set(pydash.map_(codelists.copy(), 'EA-Name')))
AttributeError: 'list' object has no attribute 'copy'

```

**Comment by DieterDePaepe** [comment]
I can answer the first question:
the CSV file is generated by using the `tsv` command of the [EA-to-RDF tool](https://github.com/Informatievlaanderen/OSLO-EA-to-RDF).

**Comment by jensscheerlinck** [comment]
Thanks @DieterDePaepe 
For the second question, the issue was that on the vocabulary (package) level, no "title" had been specified.

**Comment by jensscheerlinck** [comment]
Thanks @DieterDePaepe 
Second question was related to the python virtualenv using an older version of python.
This was resolved by created the env with the command: `virtualenv -p python3 envname`
